# pull official base image

# FROM python:3.9.6-alpine
FROM python:3.9.6-slim


# set work directory
WORKDIR /usr/src/app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install dependencies
RUN pip install --upgrade pip
COPY ./req .
RUN pip install -r req

# copy project
COPY . .
