# Generated by Django 3.2.9 on 2021-11-10 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20211110_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtosupplier',
            name='delivery',
        ),
    ]
