# Generated by Django 3.2.9 on 2021-11-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_emailtosupplier_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtosupplier',
            name='delivery',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
