# Generated by Django 3.2.9 on 2021-11-09 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_alter_lesson_unit'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='lesson',
            order_with_respect_to='name',
        ),
    ]
